### ISSUE TITLE
Code-Logic 1: Conditionally render buttons if no questions

### ISSUE THREAD

**Issue by TuanNguyen4** [RFCE2209-House-Martell/je-m-appelle-martell#101]
#### Description
The button to render more questions and answers still exists even if there are no questions in the list. 

#### Files
https://github.com/RFCE2209-House-Martell/je-m-appelle-martell/blob/b216ff742e731dfc41a21555dceeebe1e7c99736/src/components/questions/questionFooter.jsx#L7-L11

#### To Reproduce
If you click on a product that has no questions, the button to render more questions and answers is still available and clicking on them appears to do nothing.

#### Tasks (optional)
What I've done is logical AND the button element with a comparison like (questions.length > 2) so that way the button will not be there if there's two or less questions.

**Comment by fitDizzle** [comment]
Not a bad catch. Great idea, thank you and done!
