### ISSUE TITLE
Outfit Component: Removing outfit re-renders product list

### ISSUE THREAD

**Issue by Ragnaric** [RFCE2209-House-Martell/je-m-appelle-martell#105]
You can find the screenshots in my journal: https://www.notion.so/Code-Review-876406d6abef420b8d92139777fec1fc

Possible cause: After reading through your code in AddOutfitCard, I assume it was intentional to re-render the related items when adding an item; however, updating the state when removing an item probably was not intended. Unfortunately, I couldn’t find where you were handling the remove item functionality (I also searched on the OutfitCard and OutfitList modules). If it was there, I apologize for the oversight, but consider renaming the function as RemoveOutfit so that it is easier to locate.

Possible solution: I remember encountering a similar issue where I would click on the span that contained the onClick event listener, and the click itself would propagate from the child to the parent element. The solution to prevent that sort of event bubbling is to use event.stopPropagation() within the child element.

**Comment by ChristopherLeBlanc2** [comment]
It rerenders due to replacing the product back into the related products
