### ISSUE TITLE
Related Items: 429 error when browsing products

### ISSUE THREAD

**Issue by Ragnaric** [RFCE2209-House-Martell/je-m-appelle-martell#106]
Check out your code review with screenshots here: https://www.notion.so/Code-Review-876406d6abef420b8d92139777fec1fc

Possible cause: I think the issue may stem from keeping track of 3 variables in your useEffect hook as can be seen on line 34. Every time any of these variables updates, a new get request is sent to the API which overwhelms its capability to handle all the requests.

Possible solution: To be honest, I didn’t entirely solve it on my end, but I think I did manage to ameliorate it by minimizing the number of API calls. I would suggest keeping track of only one variable to update the state of the component. If I recall correctly, I was only keeping track of the current product that was displayed in the image gallery at the time. You could also consider storing all the information you need the first time around inside of a state variable so that you can then manipulate the information directly without having to make further requests; that is how I handled the search bar feature. You can see what that implementation looks like on the App.jsx if I recall correctly.

**Comment by ChristopherLeBlanc2** [comment]
I definitely need to reformat my calls in order to minimize the amount. Thanks for the possible solution.
