### ISSUE TITLE
UI-Related Issue: Closing question and answer modal on outside click

### ISSUE THREAD

**Issue by TuanNguyen4** [RFCE2209-House-Martell/je-m-appelle-martell#97]
#### Description
For me at least, I like the ability to click outside of the modal to close it. 

#### Screenshots (if ui based)
No screenshot of the issue. It's just clicking on the dim part of the region outside of the modal to close it.

#### Files
The modal component is in the following file paths:
1. src/components/questions/newAnswerModal.jsx
2. src/components/questions/newQuestionModal.jsx

#### To Reproduce
Clicking outside of the modal region does not close it.

### Suggestion
How I did this was by adding an onClick in the parent div of the modal where it will set the modal boolean to false

**Comment by fitDizzle** [comment]
Another great idea and cool learning experience. Thanks and done!
